# Generated by Django 4.2.11 on 2025-01-11 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_alter_movie_movie_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='movie_genre',
            field=models.CharField(choices=[('B', 'Biografia'), ('T', 'Terror'), ('C', 'Comedia'), ('A', 'Accion')], max_length=30),
        ),
    ]
